version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'nestjs'
    tty: true
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    command: >
      sh -c "npm run start:dev"
