services:
  app:
    image: node:20-alpine
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    user: node:node
    command: >
      sh -c "npm run start:dev"
    tty: true

  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

volumes:
  mysql_data: