services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    command: >
      sh -c "npm run start:dev"
    tty: true

  db:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

volumes:
  mysql_data: